spring:
  datasource:
    url: "jdbc:postgresql://localhost:26257/bigbench?sslmode=disable"
#    url: "jdbc:postgresql://192.168.1.99:26257/bigbench?sslmode=disable"
    username: "root"
server:
  port: 9090
model:
  csv-options:
    delimiter: ","
    allow_quoted_null: "(blank)"
    skip: "1"
  avro-options:
    strict_validation: "(blank)"
